DROP TABLE IF EXISTS USER cascade ;
CREATE TABLE USER (
    id LONG PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(30) NOT NULL ,
    surname VARCHAR(50) NOT NULL ,
    role VARCHAR(10) NOT NULL
);

DROP TABLE IF EXISTS APARTAMENT cascade ;
CREATE TABLE APARTAMENT (
    id LONG PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(50) NOT NULL ,
    price DOUBLE NOT NULL ,
    surface VARCHAR NOT NULL ,
    description VARCHAR NOT NULL ,
    apartamentstatus VARCHAR NOT NULL
);